export const titlesInputs = [
  "Client:",
  "Country:",
  "Proposal Manager:",
  "HUGHES T19 Number of Sites:",
  "Sites out of coverage:",
  "Number of Sites:",
  "Remote Spares:",
  "Total of Spares:",
  "Service Plan:",
  "Total capacity SES-17 (Mbps):",
  "Overbooking",
  "Total Ka band Capacity (Mbps):",
  "Average Mbps per Site:",
  "#¡DESCONOCIDO!",
  "Terminal Unit Price (USD) - ExWorks USA:",
  "COST - SES Ka band Mbps / Month (USD):",
  "COST - HUGHES  Ka band Mbps / Month (USD):",
  "Contract:",
  "% sites with Penalties / month:",
  "CAPEX Financing Rate:",
  "UIT:",
];

export const titlesQtos = [
  "Type",
  "Category",
  "Subcategory",
  "Manufacturer Part #",
  "Product Code",
  "Description",
  "Qty",
  "Unit of Measure",
  "Discount",
  "Finance?",
  "Unit Price",
  "Unit Disc. Price",
  "Ext. Disc. Price",
  "Unit Cost",
  "Ext. Cost",
  "Profit Margin",
  "Owner",
  "Monthly Price per Site",
  "Monthly Cost per Site",
  "Monthly Price per Mbps",
  "Monthly Cost per Mbps",
  "Financed CAPEX",
  "Financed Monthly Price per Site",
  "Notes",
];
